### ISSUE TITLE
[Action required] Add a configuration file to your project to prevent build failures

### ISSUE THREAD

**Issue by jepler** [circuitpython/CircuitPython_Org_DisplayIO_Gauge#8]
RTD requires that we take action or the doc builds will no longer work.

https://blog.readthedocs.com/migrate-configuration-v2/

**Comment by dhalbert** [comment]
Latest warnings from RTD:

> Your project(s) "circuitpython-displayio-gauge" don't have a configuration file. Configuration files will soon be required by projects, and will no longer be optional. [Read our blog post to create one](https://blog.readthedocs.com/migrate-configuration-v2/) and ensure your project continues building successfully.
> Your project(s) "circuitpython-displayio-gauge" are using the deprecated "build.image" config on their ".readthedocs.yaml" file. This config is deprecated in favor of "build.os" and will be removed on October 16, 2023. [Read our blog post to migrate to "build.os"](https://blog.readthedocs.com/build-image-config-deprecated/) and ensure your project continues building successfully.
